### ISSUE TITLE
How to reproject a raster image?

### ISSUE THREAD

**Issue by QJvic** [shengzheng1981/green-gis-js#1]
The lesson is very nice and i leanred much. But now i  have a problem, how to reproject a raster image from wgs84 to web mercator in js? I konw how to transform a point coordinate, but I have no idea of how to operate image. Could you give me some ideas please? Best wishes to you!

**Comment by shengzheng1981** [comment]
This is a really complicated problem! cause it will distort image, check this: https://stackoverflow.com/questions/4097688/draw-distorted-image-on-html5s-canvas
By the way, if only from wgs84 to web mercator, and also outof china! cause same lng  projects to  same x, same lat projects to same y. so no distortion. means the projected image also is a rectangle, you can use drawImage API.
