### ISSUE TITLE
如果设置了例如GCJO2 BD09的投影变换，fitBound会导致中心点偏移

### ISSUE THREAD

**Issue by 18134906388** [shengzheng1981/green-gis-js#2]
fitBound方法通过unproject得到的中心点坐标是偏移后的坐标，setView方法传入偏移后的坐标会再偏移一次。

**Comment by shengzheng1981** [comment]
感谢指出，暂临时调整了unproject函数，增加一original参数，以gcj02为例：
`unproject([x, y], original = false): number[] {
        const d = 180 / Math.PI;
        let [lng, lat] = [x * d / GCJ02.R, (2 * Math.atan(Math.exp(y / GCJ02.R)) - (Math.PI / 2)) * d];
        if (original) {
            if (this._type == LatLngType.GPS) {
                [lng, lat] = GCJ02.gcj02towgs84(lng, lat);
            }
        }
        return [lng, lat];
    }`
可再斟酌下，是否有更好的解决方式。
