### ISSUE TITLE
measurer和editor如果使用偏移后的投影，都会出现一些点击位置和绘制位置不一致的问题

### ISSUE THREAD

**Issue by 18134906388** [shengzheng1981/green-gis-js#5]
measurer已经修复,editor比较复杂，目前没有思路。
map.ts
`
    _onClick(event) {
        const matrix = (this._ctx as any).getTransform();
        const x = (event.offsetX - matrix.e) / matrix.a;
        const y = (event.offsetY - matrix.f) / matrix.d;
        [event.lng, event.lat] = this._projection.unproject([x, y]);
        [event.originalLng, event.originalLat] = this._projection.unproject([x, y], true);
        if (this._editor && this._editor.editing) {
            this._editor._onClick(event);
            return;
        }
        if (this._measurer && this._measurer.measuring) {
            this._measurer._onClick(event);
            return;
        }
        //this._handlers["click"].forEach(handler => handler(event));
        this.emit("click", event);
    }
`
`
_onMouseMove(event) {
        if (this._editor.editing) {
            const matrix = (this._ctx as any).getTransform();
            const x = (event.offsetX - matrix.e) / matrix.a;
            const y = (event.offsetY - matrix.f) / matrix.d;
            [event.lng, event.lat] = this._projection.unproject([x, y]);
            [event.originalLng, event.originalLat] = this._projection.unproject([x, y], true);
            this._editor._onMouseMove(event);
            return;
        }
        if (this._measurer.measuring) {
            const matrix = (this._ctx as any).getTransform();
            const x = (event.offsetX - matrix.e) / matrix.a;
            const y = (event.offsetY - matrix.f) / matrix.d;
            [event.lng, event.lat] = this._projection.unproject([x, y]);
            [event.originalLng, event.originalLat] = this._projection.unproject([x, y], true);
            this._measurer._onMouseMove(event);
            return;
        }
        if (!this._drag.flag) {
            this._handlers["mousemove"].forEach(handler => handler(event));
        }
    }
    `
measurer.ts
`_onClick(event) {
        if (!this._measuring) return;
        if (event.detail > 1) return;
        if (this._action === MeasureActionType.Polygon) {
            if (this._create.click == 0) {
                this._createLayer.clear();
                const point = new Point(event.originalLng, event.originalLat);
                const graphic = new Graphic(point, this._defaultPointSymbol);
                this._createLayer.add(graphic);
                this._create.click += 1;
                this._create.lnglats.push([event.originalLng, event.originalLat]);
            } else if (this._create.click == 1) {
                const second = new Point(event.originalLng, event.originalLat);
                const graphic1 = new Graphic(second, this._defaultPointSymbol);
                this._createLayer.add(graphic1);
                if (this._create.graphic) this._createLayer.remove(this._create.graphic);
                this._create.lnglats.push([event.originalLng, event.originalLat]);
                const line = new Polyline(this._create.lnglats);
                this._create.graphic = new Graphic(line, this._defaultLineSymbol);
                this._createLayer.add(this._create.graphic);
                this._create.click += 1;
            } else {
                const second = new Point(event.originalLng, event.originalLat);
                const graphic1 = new Graphic(second, this._defaultPointSymbol);
                this._createLayer.add(graphic1);
                if (this._create.graphic) this._createLayer.remove(this._create.graphic);
                this._create.lnglats.push([event.originalLng, event.originalLat]);
                const polygon = new Polygon([this._create.lnglats]);
                this._create.graphic = new Graphic(polygon, this._defaultPolygonSymbol);
                this._createLayer.add(this._create.graphic);
                this._create.click += 1;
            }
        } else if (this._action === MeasureActionType.Polyline) {
            if (this._create.click == 0) {
                this._createLayer.clear();
                const point = new Point(event.originalLng, event.originalLat);
                const graphic = new Graphic(point, this._defaultPointSymbol);
                this._createLayer.add(graphic);
                this._create.click += 1;
                this._create.lnglats.push([event.originalLng, event.originalLat]);
            } else {
                const second = new Point(event.originalLng, event.originalLat);
                const graphic1 = new Graphic(second, this._defaultPointSymbol);
                this._createLayer.add(graphic1);
                if (this._create.graphic) this._createLayer.remove(this._create.graphic);
                this._create.lnglats.push([event.originalLng, event.originalLat]);
                const line = new Polyline(this._create.lnglats);
                this._create.graphic = new Graphic(line, this._defaultLineSymbol);
                this._createLayer.add(this._create.graphic);
                this._create.click += 1;
            }
        }
    }
`
`
_onMouseMove(event) {
        if (!this._measuring) return;
        if (this._action === MeasureActionType.Polygon) {
            if (this._create.click == 1) {
                if (this._create.graphic) this._createLayer.remove(this._create.graphic);
                const lnglats: any = [...this._create.lnglats];
                lnglats.push([event.originalLng, event.originalLat]);
                const line = new Polyline(lnglats);
                this._create.graphic = new Graphic(line, this._defaultLineSymbol);
                this._createLayer.add(this._create.graphic);
            } else if (this._create.click > 1){
                if (this._create.graphic) this._createLayer.remove(this._create.graphic);
                const lnglats: any = [...this._create.lnglats];
                lnglats.push([event.originalLng, event.originalLat]);
                const polygon = new Polygon([lnglats]);
                this._create.graphic = new Graphic(polygon, this._defaultPolygonSymbol);
                this._createLayer.add(this._create.graphic);
            }
        } else if (this._action === MeasureActionType.Polyline) {
            if (this._create.click > 0) {
                if (this._create.graphic) this._createLayer.remove(this._create.graphic);
                const lnglats: any = [...this._create.lnglats];
                lnglats.push([event.originalLng, event.originalLat]);
                const line = new Polyline(lnglats);
                this._create.graphic = new Graphic(line, this._defaultLineSymbol);
                this._createLayer.add(this._create.graphic);
            }
        }
        this.redraw();
    }
`

**Comment by 18134906388** [comment]
代码乱码了，主要修改在event对象里面新增了两个属性originalLat originalLng，measurer中使用事件的originalLat originalLng去做操作
**
![image](https://user-images.githubusercontent.com/19529671/99513648-d1cb7480-29c5-11eb-9246-3ae51b2a5383.png)
**

**Comment by shengzheng1981** [comment]
ok! 加了合作，你可以加个注释，提交这部分代码。

**Comment by shengzheng1981** [comment]
measurer和editor，写的比较随意，满足在项目上的一个基本需求。editor其实比较复杂，确实需要有空静下心来，好好重新梳理。

**Comment by 18134906388** [comment]
已提交
